pluginManagement {
    repositories {
        google()
        mavenCentral()          // the Chaquopy Gradle plugin is published here
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "AURA"
include ":app"
